### ISSUE TITLE
Serial devices not showing

### ISSUE THREAD

**Issue by fred-bict** [flathub/org.opencpn.OpenCPN#2] opened 2022-01-22 21:05 UTC
Hi,
I am using Ubuntu 21.10 with Gnome 40.4.0.
Just installed OpenCPN 5.6.0-0 from flathub.
When I try to make a new Serial connection, dataport selector is empty
![Schermafdruk van 2022-01-22 22-02-41](https://user-images.githubusercontent.com/9447563/150655434-77b050d7-66cb-4830-b58c-4320a3de83d7.png)
.
Kind regards
Fred

**Comment by fred-bict** [comment] 2022-01-23 10:20
I (same user) can read the serial ports with GTK Term though.
Kind regards
Fred

**Comment by leamas** [comment] 2022-01-23 10:44
Hi,

Have you read the https://github.com/OpenCPN/OpenCPN/blob/master/LINUX_DEVICES.md document which is about this?

**Comment by fred-bict** [comment] 2022-01-23 20:22
Hi,
Read the document. Created udev rules as described for flatpak.
Then rebooted the system, unfortunately with no results.

**Comment by leamas** [comment] 2022-01-23 20:38
OK. What are the paths for the devices you want to use? What does `ls -l `say for these paths?   (Devices usually have paths like _/dev/ttyUSB0_ or so)

**Comment by fred-bict** [comment] 2022-01-23 21:53
A selection of some devices
![Devices](https://user-images.githubusercontent.com/9447563/150699259-b62e0ce0-900e-4f0d-89b3-c7d90d0390d8.png)
:

**Comment by leamas** [comment] 2022-01-23 22:00
hm... So, you want to use a standard serial port like ttyS0 or tty1,  is that so?

**Comment by leamas** [comment] 2022-01-23 22:08
Looking more into this, it seems that the udev rule somehow isn't in effect. Does the rule indeed contain  a line like ` KERNEL=="ttyS*", MODE="0666"` ? This line should make all  _/dev/ttys\*_ devices 666 (i. e., -rw-rw-rw) , but those devices are still 660 (-rw-rw---). 

Two questions:
  - Which device(s) do you want to use, exactly?
  - The contents of 70-serial-opencpn.rules?

**Comment by leamas** [comment] 2022-01-23 22:13
Good night for now...

**Comment by leamas** [comment] 2022-01-24 14:34
Here are two problems:

First, the devices you list are not publicly available i . e., the are 660 a. k. a. rw-rw---- instead of 666 (rw-rw-rw). The udev rule  is supposed to fix that, at least for the ttyS? devices.  However, it doesn't seem to be in effect for some reason.  The first step in understanding why is that you list the  contents of _/etc/udev/rules.d/70-serial-opencpn.rules_.

But even when this is fixed (probably some simple error), OpenCPN probes all serial ports checking that there is some device connected to it. If this probe fails it will not present the device to the user. So, just listing a bunch of serial ports makes no sense here, what's needed it the very port where you have serial hardware connected. This is most likely one of the /ttyS? devices which corresponds to com1:, com2. etc used on WIndows.

But again: the basic problem for now is  why the udev rule doesn't make ttyS? devices publicly available as it should.

**Comment by leamas** [comment] 2022-01-24 14:45
Expanding on the udev issue: I have created simple rule named _/etc/udev/rules.d/70-opencpn-serial.rules_ withe following contents:

    $ cat /etc/udev/rules.d/70-opencpn-serial.rules
    KERNEL=="ttyS*", MODE="0666"
    $
I then reloaded all rules as root: 

    # udevadm control --reload-rules && udevadm trigger

Listing my serial ports I see that they are all accessible to everyone: 

    $ ls -l /dev/ttyS[0-2]
    crw-rw-rw- 1 root dialout 4, 64 Jan 24 15:38 /dev/ttyS0
    crw-rw-rw- 1 root dialout 4, 65 Jan 24 15:38 /dev/ttyS1
    crw-rw-rw- 1 root dialout 4, 66 Jan 24 15:38 /dev/ttyS2
    $

What happens if you make the same steps?




_

**Comment by fred-bict** [comment] 2022-01-24 18:39
Hi,
I use the ttyUSB0 as a device, as you can see in the list above, mail 23 jan. Showing tty* was just for reference.
Defined udev rule: KERNEL=="ttyUSB*", MODE="0666"
The next step, as root, I restarted udev service with: 
$ sudo systemctl restart udev
That had effect on /dev/ttyUSB0 file permissions, as you can see in the list above: crw-rw-rw- 1 root dialout ...

Today (next) executed:
$ sudo udevadm control --reload-rules
$ sudo udevadm trigger

Next restart openCPN
OpenCPN Data port selection values are still empty.

Actual settings.
![Devices 20220124](https://user-images.githubusercontent.com/9447563/150843319-5c5646ff-08f8-4dca-bbbe-6fefae96d7f0.png)
.

**Comment by leamas** [comment] 2022-01-24 19:10
hm... some progress, but we are not there. 

The problem is that my own serial port is at my boat, some kilometers away on land, waiting for the ice to disappear. 

In the meantime: with the ttyUSB0 device connected, restart OpenCPN using the `--loglevel debug` option. And post the logfile  at  _.var/app/org.opencpn.OpenCPN/config/opencpn/opencpn.log_. 

For some reason github does not accept plain text attachments, so compress the log before attaching it.

**Comment by fred-bict** [comment] 2022-01-25 10:57
Log file shows 1 error:
- pluginmanager.cpp:1891 Could not open file "opencpn" for reading with errno = 2.

BTW: when starting opencpn from cmd line, flatpak run shows errors on GTK Module.

[OpenCPN.NoDevices.log.tar.gz](https://github.com/flathub/org.opencpn.OpenCPN/files/7932918/OpenCPN.NoDevices.log.tar.gz)

**Comment by leamas** [comment] 2022-01-25 11:15
That error is not  significant, just to forget.

What is significant is that I *think* this might be a configuration bug, a flag  used to define how serial ports are enumerated seems lost. In short, I need some time to get to my boat, fetch the serial adapter and do more testing. I also need to read up  more, I did the PR which basically handles this but it was some time ago.

Hopefully, you are in the Northern hemisphere and doesn't sail these days?

**Comment by leamas** [comment] 2022-01-26 15:18
I have been doing more debugging. One problem seems to be a missing configuration option, but this needs to be verified.

I have been debugging with a serial USB port connected. However, the test in ser_ports.cpp around line 150 fails. I assume that this is because nothing is connected to the serial port. This test has not changed in quite some time, so this is "just" a testing issue. I will try to test with everything connected  somehow. 

I presume that you have been testing with the GPS connected, right?

Stay tuned.

**Comment by fred-bict** [comment] 2022-01-26 18:06
See picture from GTKterm using ttyUSB0

![Schermafdruk van 2022-01-26 19-03-34](https://user-images.githubusercontent.com/9447563/151220807-28c5a40d-267b-44e4-8b80-885b83545a23.png)

**Comment by leamas** [comment] 2022-01-27 13:12
Did some more testing on my laptop which I occasionally also use in the boat. Here, the device link I have setup does work, while /dev/ttyUSB[0-9] does not. This basically means that while there is a bug that needs to be fixed, here is a work-around.

Could you try to create a  device linke as described in LINUX_DEVICES.md, the "Fixed device names" part? If everything is as it should, that link should be visible in the UI. Using a device link is BTW a Goof Thing anyway.

Again: here is a bug we  need to explore and eventually fix., But this might be a work-around for now.

**Comment by leamas** [comment] 2022-01-27 13:43
hm... More checking. The core issue is indeed that the test in ser_ports.cpp around line 150 fails. This is a new behaviour, it didn't use to.

What is your kernel version i. e., what does `uname -r`say?

**Comment by fred-bict** [comment] 2022-01-27 14:53
Linux kernel 5.13.0-27, currently the latest version.
Succes!

**Comment by leamas** [comment] 2022-01-27 15:05
> Linux kernel 5.13.0-27, currently the latest version.

On slow Ubuntu, yes. I'm on Fedora running 5.15.16

> Succes!

Great!

**Comment by leamas** [comment] 2022-01-27 15:14
We have two broken computers and one working. The broken ones are running kernels 5.13.0-27 and 5.15.16-100, the working one 5.12.15-200. 

The hairy details: ser_ports.cpp does a test around line 150, basically `ioctl(fd, TIOCGSERIAL, &serinfo) == 0` which succeeds.  The code tests for serinfo.type being != 0 as a sign the port is usable. On the  5.12.15-200. machine this works, but on at least the 5.15.16-100 one it fails, serinfo.type is 0.

We do need the test, otherwise there are  100 possible ports which is too much to handle in the UI.

Back to drawing board and some advice from Dr Google

**Comment by leamas** [comment] 2022-01-27 15:33
Moving this issue to https://github.com/OpenCPN/OpenCPN/issues/2528, this is not a Flatpak issue

**Comment by leamas** [comment] 2022-01-30 11:27
A new update 5.6.0-2+777652e  has been pushed to master branch for this issue. 

Note that despite the update devices still must be accessible as described in [LINUX_DEVICES.md](https://github.com/OpenCPN/OpenCPN/blob/master/LINUX_DEVICES.md)

Thanks for an important report and help with debugging!

**Closed by leamas** 2022-01-30 11:27 UTC
